### ISSUE TITLE
1.16.5 Server crash when I try to get into the hive of mod The Bumblezone

### ISSUE THREAD

**Issue by ghost** [ItsBlackGear/CavesAndCliffsBackport#2]
Hi, I tracked down a strange bug causing the server to crash. If you try to move to the hive using ender pearl, then after a few seconds the server crashes with an error.
Forge-1.16.5-36.2.9
Сavesandcliffs-1.16.5-7.1
The_bumblezone_forge-2.6.5+1.16.5

Crash report
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 06.11.2021, 1:51
Description: Exception in server tick loop

java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/blackgear/cavesandcliffs/common/blocks/CandleBlock
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
Caused by: java.lang.NoClassDefFoundError: com/blackgear/cavesandcliffs/common/blocks/CandleBlock
	at com.telepathicgrunt.the_bumblezone.modcompat.CavesAndCliffsBackportCompat.CACGetRandomCandle(CavesAndCliffsBackportCompat.java:50) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.processors.BeeDungeonProcessor.func_230386_a_(BeeDungeonProcessor.java:116) ~[the_bumblezone:2.6.5] {re:classloading}
	at net.minecraft.world.gen.feature.template.StructureProcessor.process(StructureProcessor.java:18) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.processBlockInfos(Template.java:378) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:222) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at com.telepathicgrunt.the_bumblezone.world.features.NbtFeature.place(NbtFeature.java:57) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.place(BeeDungeon.java:26) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.func_241855_a(BeeDungeon.java:13) ~[the_bumblezone:2.6.5] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:cavebiomeapi.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.blackgear.cavesandcliffs.common.blocks.CandleBlock
	at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at com.telepathicgrunt.the_bumblezone.modcompat.CavesAndCliffsBackportCompat.CACGetRandomCandle(CavesAndCliffsBackportCompat.java:50) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.processors.BeeDungeonProcessor.func_230386_a_(BeeDungeonProcessor.java:116) ~[the_bumblezone:2.6.5] {re:classloading}
	at net.minecraft.world.gen.feature.template.StructureProcessor.process(StructureProcessor.java:18) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.processBlockInfos(Template.java:378) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:222) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
	at com.telepathicgrunt.the_bumblezone.world.features.NbtFeature.place(NbtFeature.java:57) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.place(BeeDungeon.java:26) ~[the_bumblezone:2.6.5] {re:classloading}
	at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.func_241855_a(BeeDungeon.java:13) ~[the_bumblezone:2.6.5] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:cavebiomeapi.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
	... 11 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
		at com.telepathicgrunt.the_bumblezone.modcompat.CavesAndCliffsBackportCompat.CACGetRandomCandle(CavesAndCliffsBackportCompat.java:50) ~[the_bumblezone:2.6.5] {re:classloading}
		at com.telepathicgrunt.the_bumblezone.world.processors.BeeDungeonProcessor.func_230386_a_(BeeDungeonProcessor.java:116) ~[the_bumblezone:2.6.5] {re:classloading}
		at net.minecraft.world.gen.feature.template.StructureProcessor.process(StructureProcessor.java:18) ~[?:?] {re:classloading}
		at net.minecraft.world.gen.feature.template.Template.processBlockInfos(Template.java:378) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
		at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:222) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
		at net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:world.TemplateAccessor,pl:mixin:A}
		at com.telepathicgrunt.the_bumblezone.world.features.NbtFeature.place(NbtFeature.java:57) ~[the_bumblezone:2.6.5] {re:classloading}
		at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.place(BeeDungeon.java:26) ~[the_bumblezone:2.6.5] {re:classloading}
		at com.telepathicgrunt.the_bumblezone.world.features.BeeDungeon.func_241855_a(BeeDungeon.java:13) ~[the_bumblezone:2.6.5] {re:classloading}
		at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
		at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?] {}
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
		at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
		at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
		at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
		at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:cavebiomeapi.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
		at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
		at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:A}
		at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
		at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
		at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
		at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
		at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
		at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by ItsBlackGear** [comment]
Seems to be an issue from bumblezone side, i will report this to telepathic
grunt, thanks for letting me know

**Comment by ItsBlackGear** [comment]
we've located the problem and i did a small oopsie with a refactor, it shall be fixed in the next hotfix c:

**Comment by ghost** [comment]
Thank you)

**Comment by ItsBlackGear** [comment]
Good news, you'll get a hotfix for this tomorrow ^^

**Comment by ItsBlackGear** [comment]
fixed in 7.1.2
