### ISSUE TITLE
Exception during compostable initialization due to lack of thread safety

### ISSUE THREAD

**Issue by Johni0702** [ItsBlackGear/CavesAndCliffsBackport#56]
The static Object2FloatMap in ComposterBlock is not thread safe and as such must not be modified (or accessed in general) from anywhere but the main thread. CavesAndCliffsBackport however seems to modify it from its `FMLCommonSetupEvent` handler ([which is called for multiple mods in parallel, and therefore must not access anything that's not thread-safe](https://github.com/MinecraftForge/MinecraftForge/blob/09f1b8d43856643e4ab36d9d64e2176c440a3e72/src/main/java/net/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent.java#L23-L24)). As such, errors like this one can randomly happen when another mod (or vanilla) tries to modify the map at the same time:
```
java.lang.ArrayIndexOutOfBoundsException: 256
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at com.blackgear.cavesandcliffs.core.other.BlockInteraction.setCompostable(BlockInteraction.java:56) ~[?:1.16.5-7.2.0] {re:classloading}
	at com.blackgear.cavesandcliffs.core.other.BlockInteraction.registerCompostables(BlockInteraction.java:31) ~[?:1.16.5-7.2.0] {re:classloading}
	at com.blackgear.cavesandcliffs.core.other.BlockInteraction.bootstrap(BlockInteraction.java:16) ~[?:1.16.5-7.2.0] {re:classloading}
	at com.blackgear.cavesandcliffs.core.CavesAndCliffs.commonSetup(CavesAndCliffs.java:70) ~[?:1.16.5-7.2.0] {re:classloading}
	at com.blackgear.cavesandcliffs.core.CavesAndCliffs$$Lambda$4135/1990356023.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2984/1941665837.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3230/1474835976.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3327/1212396383.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
```
[Crash Report](https://cdn.discordapp.com/attachments/1095723820930842744/1095724112569176104/crash-2023-03-24_16.18.26-fml.txt)

**Comment by Cristelknight** [comment]
@Johni0702 When would i add the compostables then?

**Comment by Johni0702** [comment]
> @Johni0702 When would i add the compostables then?

I don't know if there's a dedicated way in Forge to register compostables in particular, but the documentation I linked does clearly state how to enqueue arbitrary work to run on the main thread from this event.

**Comment by Cristelknight** [comment]
yeah. i also saw it after writing my comment. that’s why you should read first before asking
